language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "iojs"
before_install:
  - npm config set registry http://registry.npmjs.org/
  - export NODE_TLS_REJECT_UNAUTHORIZED=0
  - npm config set strict-ssl false
  - npm install -g npm@~1.4.6
